"""Repository interfaces for storage abstraction."""

from __future__ import annotations

from typing import Protocol

from ..models import (
    AgreementVersion,
    Assignment,
    DerivedConstraint,
    DriftReport,
    Household,
    Member,
    MonitoringSignal,
    PrivateInterviewSession,
    RenegotiationCycle,
)


class HouseholdRepository(Protocol):
    def create(self, household: Household) -> Household: ...
    def get(self, household_id: str) -> Household | None: ...
    def list(self) -> list[Household]: ...
    def clear(self) -> None: ...


class MemberRepository(Protocol):
    def add(self, household_id: str, member: Member) -> Member: ...
    def get(self, member_id: str) -> Member | None: ...
    def list_by_household(self, household_id: str) -> list[Member]: ...
    def clear(self) -> None: ...


class InterviewRepository(Protocol):
    def create(self, session: PrivateInterviewSession) -> PrivateInterviewSession: ...
    def get(self, session_id: str) -> PrivateInterviewSession | None: ...
    def list_by_household(self, household_id: str) -> list[PrivateInterviewSession]: ...
    def list_by_member(self, member_id: str) -> list[PrivateInterviewSession]: ...
    def update(self, session: PrivateInterviewSession) -> PrivateInterviewSession: ...
    def clear(self) -> None: ...


class ConstraintRepository(Protocol):
    def create_many(self, constraints: list[DerivedConstraint]) -> list[DerivedConstraint]: ...
    def list_by_member(self, member_id: str) -> list[DerivedConstraint]: ...
    def list_shareable_by_household(self, household_id: str) -> list[DerivedConstraint]: ...
    def list_by_ids(self, constraint_ids: list[str]) -> list[DerivedConstraint]: ...
    def clear(self) -> None: ...


class AgreementRepository(Protocol):
    def create(self, agreement: AgreementVersion) -> AgreementVersion: ...
    def get(self, agreement_id: str, version: int) -> AgreementVersion | None: ...
    def list_versions(self, agreement_id: str) -> list[AgreementVersion]: ...
    def list_by_household(self, household_id: str) -> list[AgreementVersion]: ...
    def latest_by_household(self, household_id: str) -> AgreementVersion | None: ...
    def update(self, agreement: AgreementVersion) -> AgreementVersion: ...
    def clear(self) -> None: ...


class AssignmentRepository(Protocol):
    def create(self, assignment: Assignment) -> Assignment: ...
    def create_many(self, assignments: list[Assignment]) -> list[Assignment]: ...
    def get(self, assignment_id: str) -> Assignment | None: ...
    def list_by_household(self, household_id: str) -> list[Assignment]: ...
    def list_by_member(self, member_id: str) -> list[Assignment]: ...
    def list_by_agreement(self, agreement_id: str, version: int) -> list[Assignment]: ...
    def update(self, assignment: Assignment) -> Assignment: ...
    def clear(self) -> None: ...


class MonitoringRepository(Protocol):
    def create(self, signal: MonitoringSignal, household_id: str) -> MonitoringSignal: ...
    def list_by_household(self, household_id: str) -> list[MonitoringSignal]: ...
    def list_by_member(self, member_id: str) -> list[MonitoringSignal]: ...
    def clear(self) -> None: ...


class DriftRepository(Protocol):
    def create(self, report: DriftReport, household_id: str) -> DriftReport: ...
    def get(self, drift_id: str) -> DriftReport | None: ...
    def list_by_household(self, household_id: str) -> list[DriftReport]: ...
    def clear(self) -> None: ...


class RenegotiationRepository(Protocol):
    def create(self, cycle: RenegotiationCycle) -> RenegotiationCycle: ...
    def get(self, renegotiation_id: str) -> RenegotiationCycle | None: ...
    def update(self, cycle: RenegotiationCycle) -> RenegotiationCycle: ...
    def list_by_household(self, household_id: str) -> list[RenegotiationCycle]: ...
    def clear(self) -> None: ...
